### ISSUE TITLE
Jekyll Theme - "modern-resume"

### ISSUE THREAD

**Issue by Pabloin** [Pabloin/pabloin#2]
Jekyll Theme - "modern-resume"

based on: https://jekyll-themes.com/modern-resume

- [x] Develop
- [x] Install
- [x] Branch "WOOD" and install local 

**TODO:**
Next Ones:
- [ ] Setup all texts that I want
- [ ] associate with simple (pabloin.github.io)
- [ ] associate with .ar domain 

---
This is 
"Wood" Release

**Comment by Pabloin** [comment]
- [x]  Branch "WOOD" and install local

After install local Jekyll (following officail https://jekyllrb.com/)

```
bundle install
bundle exec jekyll serve
```

![image](https://user-images.githubusercontent.com/21208987/121833620-1b054d80-cca3-11eb-8c6d-4eae18191830.png)
